version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=1234
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=harry
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
